### ISSUE TITLE
Self-reported score

### ISSUE THREAD

**Issue by micronet-challenge-submissions** [binhdt95/Jaist-MicroNet-Challenge#1]
Hello! Thanks so much for your entry! We just had a couple questions:

1. From your README it looks like your entry achieves 34.71ppl if I'm not mistaken, but I'm not 100% sure what your self reported score is. In the table in your README, are those FLOPs all 32-bit or do they take into account the freebie quantization? Do you parameter count numbers take into account the freebie quantization as well? Assuming they both take into account the freebie scoring already, then your self-reported score would be:

52.45275 / 159 + 156.857 / 318 = 0.8231525157

Is this correct? Note that I converted your parameter count into # of 32-bit parameter since we define 1 parameter as a 32-bit parameter. 

2. What name would you like your entry published under?
3. What email would you like for us to use to contact you?

Thanks!
Trevor

**Comment by binhdt95** [comment]
Hi! Thank for your questions. This is our answers:
    1. Your assumption is correct. 
    2. Team's name is JNLP.
    3. You can contact with email: s1920422@jaist.ac.jp

Thanks!
Binh

**Comment by micronet-challenge-submissions** [comment]
Thanks for the information! One other question - out test environment only supports up to python 3.6 and I'm getting an error with your use of "defaults" in namedtuple

**Comment by micronet-challenge-submissions** [comment]
Woops accidentally hit a

**Comment by micronet-challenge-submissions** [comment]
Thanks for the information! Ignore my floundering:)
